<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>go</string>
	</array>
	<key>firstLineMatch</key>
	<string>-\*- C\+\+ -\*-</string>
	<key>foldingStartMarker</key>
	<string>(?x)
		 /\*\*(?!\*)
		|^(?![^{]*?//|[^{]*?/\*(?!.*?\*/.*?\{)).*?\{\s*($|//|/\*(?!.*?\*/.*\S))
	</string>
	<key>foldingStopMarker</key>
	<string>(?&lt;!\*)\*\*/|^\s*\}</string>
	<key>name</key>
	<string>Go (Colorcode)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f|ll|LL|ull|ULL)?\b</string>
			<key>name</key>
			<string>constant.numeric.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>"(\\[rnt\\"]|[^"])*"</string>
			<key>name</key>
			<string>string.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>`[^']*`</string>
			<key>name</key>
			<string>string.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>'[^']*'</string>
			<key>name</key>
			<string>string.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>//.*</string>
			<key>name</key>
			<string>comment.go</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(package|import|range|for|if|go|defer|func|var|_)\b</string>
			<key>name</key>
			<string>keywords.go</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\w+\b</string>
			<key>name</key>
			<string>colorize.go</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.go</string>
</dict>
</plist>
